# Welcome message when a player enters the server
welcome_message: welcome %playername%~
# End of Round Message
round_end_info: The round is over！dont leave yet，See you next roundヾ(￣▽￣)~
# Message players will receive when Friendly Damage is enabled
f_f_message: <align=center><voffset=28em> <color=#F6511D> ~Friendly damage is enabled~ </color></voffset></align>
# Server Broadcast Text
auto_server_message_text: server broadcast
# Title of the message list in the chat
chat_message_title: 'Message list:'
# The name of each message in the chat
message_type_name:
  AdminPrivateChat: Manage private chats
  BroadcastChat: public news
  TeamChat: Teammate news.
# Chat system custom player character name
chat_system_role_translation:
  ClassD: D-class personnel
  FacilityGuard: security guard
  ChaosConscript: Chaos Conscript
  ChaosMarauder: Chaos Raider
  ChaosRepressor: Chaos Suppressor
  ChaosRifleman: Chaos Rifleman
  NtfCaptain: Nine Tailed Fox Commander
  NtfPrivate: Nine Tailed Fox Private
  NtfSergeant: Nine-Tailed Fox Sergeant
  NtfSpecialist: Nine-tailed fox containment expert
  Scientist: Scientist
  Tutorial: Tutorial
  Scp096: Scp-096
  Scp049: SCP-049
  Scp173: SCP-173
  Scp939: SCP-939
  Scp079: SCP-079
  Scp0492: SCP-049-2
  Scp106: SCP-106
  Scp3114: SCP-3114
  Spectator: observer
  Overwatch: supervision
  Filmmaker: director
# Chat system custom player team names
chat_system_team_translation:
  Dead: death camp
  ClassD: DD camp
  OtherAlive: mysterious camp
  Scientists: PhD camp
  SCPs: SCP camp
  ChaosInsurgency: Chaos camp
  FoundationForces: Nine-tailed fox camp
# Administrator monitoring output text
admin_log: '%Nickname%exist%Time%when | Used the command:%Command% | Steam64ID:%UserId%'
# Administrator monitoring command broadcast
admin_log_broadcast: '<size=30>[<color=red>Management behavior monitoring output record</color>] <%Nickname%> Just used the command: %Command%</size>'
# Shows the time left until startup and server status
title_text: <size=50><color=#F0FF00><b>Waiting for players, {seconds}</b></color></size>
# Text showing the number of players
player_count_text: <size=40><color=#FFA600><i>{players}</i></color></size>
# Message displayed if the lobby is locked
server_pause_text: Server is paused
# The second line of the message
second_left_text: left {seconds}
# Multi-line messages
seconds_left_text: left {seconds}
# The message displayed when the round starts
round_start_text: Round starts
# The message displayed when a player joins the server
player_join_text: Players join
# Message displayed when multiple players join the server
players_join_text: players joined
# Guard mutiny announcement
guard_mutiny_broadcast: <size=60><color=#ff0000ff>[warn]</color>The guards at this facility have been turned against by the Chaos Insurgency.</size>
# Announcement displayed by guards for elite teams
elite_guard_broadcast: <size=60><color=#00ffffff>[notify]</color>The guards of this facility are nine-tailed fox elite members，Security strength greatly increased</size>
# Watch List Title
watch_list_title: <align=right><size=45%><color=(COLOR)><b>observer ((COUNT)):</b></color></size></align>
# Watch List Format
names: <align=right><size=45%><color=(COLOR)><br>(NAME)</color></size></align>
# DNT Reminder
d_n_t_warning: You turned on DNT，please close，Otherwise some plug-ins will not work properly
# SCP-073 Reasons for Anti-Injury
s_c_p073_damage_reason: SCP073 counter-injury
# SCP-029 Escape Facility Hint
s_c_p029_escape_hint: Successfully escape the facility and become Chaos to receive a legacy from the Chaos Insurgency.
# SCP-703 Escape Facility Hint
s_c_p703_escape_hint: Successfully escaped from the facility and became a nine-tailed fox containment expert，Get 3x
# Skynet Mobile Task Force Cassie Broadcast
skynet_cassie: Mobile Task Forces Kappa-10 and Mu-7, codenamed Skynet, have entered the facility. They will help Dancer One contain SCP-079. All surviving personnel are advised to follow standard evacuation protocols until the MTF team arrives at your location. Currently, there are still %SCPNum% SCPs
# Skynet Mobile Task Force Skill Description
skynet_skill_introduction:
- You are [Skynet Mobile Task Force member] Cherish the ghost lantern in your hand
- The generator you start will <color=red>activate soon</color>
# Skynet Mobile Task Force New Recruit Broadcast
skynet_private_broadcast: <size=70><color=#0051FF>You are a Mobile Task Force-Skynet recruit</color></size>
# Skynet Mobile Task Force Recruit Custom Information
skynet_private_custom_info: Skynet recruits
# Skynet Mobile Task Force Sgt.
skynet_sergeant_broadcast: <size=70><color=#0051FF>You are the Mobile Task Force-Skynet, Sgt.</color></size>
# Skynet Mobile Task Force Recruit Custom Information
skynet_sergeant_custom_info: Skynet Sergeant
# Skynet Mobile Task Force Commander Broadcast
skynet_captain_broadcast: <size=70><color=#0051FF>You are the commander of Mobile Task Force-Skynet</color></size>
# Skynet Mobile Task Force Commander Custom Message
skynet_captain_custom_info: Skynet Commander
# See No Evil Mobile Task Force Cassie Broadcast
see_no_evil_cassie: Mobile Task Force Eta-10, codenamed See No Evil, has entered the facility. They will help contain SCP-096. It is recommended that all surviving personnel implement standard evacuation protocols until the MTF team arrives at your location. There are currently %SCPNum% SCPs left.
# See No Evil Mobile Task Force Skill Description
see_no_evil_skill_introduction:
- You are [Member of the Mobile Task Force No Evil], dare to stare at SCP096
- He is <color=red>difficult</color> to kill. You can just stare at him as long as he is not violent.
# See No Evil Mobile Task Force New Recruit Broadcast
see_no_evil_private_broadcast: <size=70><color=#0051FF>You are Mobile Task Force-See No Evil Recruit</color></size>
# See No Evil Mobile Task Force New Recruit Custom Message
see_no_evil_private_custom_info: See no evil recruits
# See No Evil Mobile Task Force Sergeant Broadcast
see_no_evil_sergeant_broadcast: <size=70><color=#0051FF>Youre Mobile Task Force-See No Evil, Sgt.</color></size>
# See No Evil Mobile Task Force New Recruit Custom Message
see_no_evil_sergeant_custom_info: See no evil, Sergeant
# Mobile Task Force Commander Broadcast
see_no_evil_captain_broadcast: <size=70><color=#0051FF>You are Mobile Task Force-See No Evil Commander</color></size>
# See No Evil Mobile Task Force Commander Custom Message
see_no_evil_captain_custom_info: See no evil, Commander
# Special character is contained Cassie suffix
special_role_contain_cassie: Successfully eliminated, the specific reason is unknown
# Chaos leader name
chaos_leader_role_name: Chaos Leader
# Chaos Leader Refresh Broadcast
chaos_leader_spawn_broadcast: <size=80><color=#00ff00ff>You are the leader of the Chaos Insurgency</color></size>
# Chaos Leader Death Cassie
chaos_leader_death_cassie: Chaos leader dies
# SCP-2936-1Refresh Broadcast
s_c_p29361_spawn_broadcast: <size=70>Who are you <color=red>SCP-2936-1 giant german robot</color></size>
# SCP-2936-1 Skill Introduction
s_c_p29361_skill_introduction: Who are you [SCP-2936-1] You have a huge body and thick blood
# SCP-073 Abel Refresh Broadcast
s_c_p073_abel_spawn_broadcast: Who are you<color=green>SCP-073 Abel</color>
# SCP-073 Abel Skill Introduction
s_c_p073_abel_skill_introduction: Who are you[SCP-073] you will be passive<color=red>rebound</color>Partial damage to the enemy
# SCP-073 Cain refreshes broadcast
s_c_p073_cain_spawn_broadcast: Who are you<color=green>SCP-073 Cain</color>
# SCP-073 Cain Skill Introduction
s_c_p073_cain_skill_introduction: Who are you [SCP-073] You have<color=red>unlimited</color>Self-healing ability, stop and take a rest
# SCP-703 Refresh Broadcast
s_c_p703_spawn_broadcast: <size=80><color=#00ffffff>You are SCP-703</color></size>
# SCP-703 Skill Introduction
s_c_p703_skill_introduction:
- You are [SCP-703] and you will get random items every once in a while.
- <color=red>%Time% </color> until the next time you get the item
# SCP-703 Get item hint
s_c_p703_received_item_hint: get an item
# SCP-029 Refresh Broadcast
s_c_p029_spawn_broadcast: <size=60><color=#ff0000ff>You are SCP-029 Daughter of Shadow</color></size>
# SCP-029 Skill Introduction
s_c_p029_skill_introduction: you are[SCP-029] you have<color=red>unlimited</color>speed bonus
# SCP-347 Refresh Broadcast
s_c_p347_spawn_broadcast: you are<color=red>SCP-347 invisible woman</color>
# SCP-347 Skill Introduction
s_c_p347_skill_introduction:  you are [SCP-347] you<color=red>forever</color> Are invisible, but you dont move around
# SCP-1093 Refresh Broadcast
s_c_p1093_spawn_broadcast: you are<color=yellow>SCP-1093 human lamp</color>
# SCP-1093 Skills
s_c_p1093_skill_introduction:
- You are [SCP-1093], which continuously illuminates a nearby 5-meter range and radiates people within a 1-meter nearby range.
- Your head is nothing, no one can do any harm to your head
# Guard Captain refreshes broadcast
guard_captain_spawn_broadcast: <size=60><color=#E5DADA>You are the security captain</color></size>
# SCP-191 Refresh Broadcast
s_c_p191_spawn_broadcast: you become <color=red>SCP-191 Mechanical girl</color>
# SCP-191 Skill Introduction
s_c_p191_skill_introduction:
- You are [SCP-191] because of your body modifications
- You are <color=red>very resistant</color> to everything except electromagnetic and explosive damage.
- But don’t forget to go to the 079 containment room to recharge
# SCP-191 battery level display
s_c_p191_battery_hint_show: <align=right><size=40><b>Your current remaining battery capacity:<color=yellow>%Battery%install</color></size></b></align>
# SCP-191 Cause of death due to battery exhaustion
s_c_p191_battery_depletion_death_reason: Battery exhausted
# SCP-1056 Minimizer Pickup Hint
s_c_p1056_pickup_hint: you picked it up<color=red>SCP-1056</color> reducer!
# SCP-1056 Reducer using Hint
s_c_p1056_used_hint: boom!you become smaller!!!
# SCP-1068 Harmless Nuclear Bomb Pickup Hint
s_c_p1068_pickup_hint: you picked up<color=red>SCP-1068</color> harmless nuclear bomb!
# SCP-1056 Harmless Nuclear Bomb Use Broadcast
s_c_p1068_used_broadcast: Someone used<color=red>SCP-1068</color> harmless nuclear bomb!
# SCP-029 Special Introduction
s_c_p029_special_introduction: <color=red>SCP-029 Daughter of Shadow</color>
# SCP-703 Special Introduction
s_c_p703_special_introduction: <color=blue>SCP-703 in the closet</color>
# SCP-347 Special Introduction
s_c_p347_special_introduction: <color=red>SCP-347 invisible woman</color>
# SCP-1093 Special Introduction
s_c_p1093_special_introduction: <color=yellow>SCP-1093 human lamp</color>
# SCP-073 Abel Special Introduction
s_c_p073_abel_special_introduction: <color=green>SCP-073 Abel</color>
# SCP-073 Cain Special Introduction
s_c_p073_cain_special_introduction: <color=green>SCP-073 Cain</color>
# SCP-191 Special Introduction
s_c_p191_special_introduction: <color=red>SCP-191 Mechanical girl</color>
# SCP-2936 Special Introduction
s_c_p2936_special_introduction: <color=red>SCP-2936-1 giant german robot</color>
# Skynet Mobile Task Force Special Introduction
skynet_special_introduction: <color=blue>Skynet Mobile Task Force</color>
# See No Evil Mobile Task Force Special Introduction
see_no_evil_special_introduction: <color=blue>Look No Evil Mobile Task Force</color>
